# Generated by Django 6.0.2 on 2026-02-26 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answerscript',
            name='answer_resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_answer', to='teachers.resource'),
        ),
        migrations.AddField(
            model_name='answerscript',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_scripts', to='teachers.exam'),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='teachers.course'),
        ),
        migrations.AddField(
            model_name='answerscript',
            name='registered_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.registeredcourse'),
        ),
        migrations.AddField(
            model_name='review',
            name='registered_course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_review', to='students.registeredcourse'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='registeredcourse',
            unique_together={('student', 'course')},
        ),
    ]
