# Generated by Django 6.0.2 on 2026-02-26 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('marks', models.PositiveIntegerField(default=100)),
                ('exam_type', models.CharField(choices=[('mcq', 'MCQ'), ('subjective', 'Subjective'), ('both', 'Both')], max_length=15)),
                ('instruct_ai', models.TextField(help_text='Custom instructions for AI evaluation/proctoring')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='teachers.course')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('question', 'Question Script'), ('answer', 'Answer Key'), ('outline', 'Course Outline'), ('lecture', 'Lecture Material')], max_length=20)),
                ('media', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('script', models.JSONField(blank=True, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_resources', to='teachers.exam')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='course_outline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_outline', to='teachers.resource'),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_script',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_qs_script', to='teachers.resource'),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_summary', models.TextField(help_text='Summary of student performance')),
                ('suggestion_text', models.TextField(help_text='AI recommended study path')),
                ('is_ai_suggestion', models.BooleanField(default=True)),
                ('registered_course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='students.registeredcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, help_text='e.g. Senior Lecturer', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
