# Generated by Django 5.1.7 on 2026-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_exam_course_outline_course_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
