# Generated by Django 5.1.7 on 2026-03-28 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_exam_duration_minutes_exam_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='answer_key',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_answer_key', to='teachers.resource'),
        ),
    ]
