# Generated by Django 5.1.7 on 2026-03-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_exam_answer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ai_generation_done',
            field=models.BooleanField(default=False, help_text='Indicates if AI has completed generating the QS and Answer Key'),
        ),
    ]
