# Generated by Django 5.1.7 on 2026-03-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_exam_ai_generation_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='answer_key',
        ),
    ]
