# Generated by Django 5.1.7 on 2026-03-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_remove_exam_answer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
    ]
